# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: can_drive.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'can_drive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61n_drive.proto\x12\x03\x64\x65m\"T\n\x0f\x43\x61nDriveRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x13\n\x0b\x61zimuth_deg\x18\x03 \x01(\x01\x12\x12\n\ndistance_m\x18\x04 \x01(\x01\"n\n\x10\x43\x61nDriveResponse\x12-\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1f.dem.CanDriveResponse.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'can_drive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDRIVERESPONSE_DATAENTRY']._loaded_options = None
  _globals['_CANDRIVERESPONSE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_CANDRIVEREQUEST']._serialized_start=24
  _globals['_CANDRIVEREQUEST']._serialized_end=108
  _globals['_CANDRIVERESPONSE']._serialized_start=110
  _globals['_CANDRIVERESPONSE']._serialized_end=220
  _globals['_CANDRIVERESPONSE_DATAENTRY']._serialized_start=177
  _globals['_CANDRIVERESPONSE_DATAENTRY']._serialized_end=220
# @@protoc_insertion_point(module_scope)
